services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - dwp-smkn4-malang-db-net
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - dwp-smkn4-malang-db-net
    volumes:
      - ./pma-data:/var/lib/mysql

networks:
  dwp-smkn4-malang-db-net:
    driver: bridge
